---
# ClusterLogForwarder for Telco Hub
# Forwards audit and infrastructure logs to Kafka with hub-specific labeling
apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    # Deploy after cluster logging operator is ready
    argocd.argoproj.io/sync-wave: "-30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    # Ignore controller-managed status differences in ArgoCD
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  # Filters add metadata labels to log records for identification
  {{- if .spec.filters }}
  filters:
    {{- .spec.filters | toYaml | nindent 2 }}
  {{- end }}

  # Output destinations for log forwarding
  outputs:
  - name: hub-kafka-output
    type: kafka
    kafka:
      # Kafka broker endpoint -> update for your environment!
      url: "^(tcp|http|https)://.*$"

  # Pipelines define which logs go where with what processing
  pipelines:
  - # Apply labeling filter to identify log source. NOTE: filterRefs MUST be first
    {{- if .filterRefs }}
    filterRefs:
    {{- .filterRefs | toYaml | nindent 4 }}
    {{- else }}
    filterRefs:
    - telco-hub-labels
    {{- end }}
    # Log types to forward (excludes application logs for hub). NOTE: inputRefs second
    inputRefs:
    - audit
    - infrastructure
    name: telco-hub-logs
    # Where to send the logs
    outputRefs:
    - hub-kafka-output

  # Service account for log collection
  serviceAccount:
    name: collector
