{{- if .Values.telcoHub.components.lso.enabled }}
---
# Local Storage Operator - Referenced from existing telco-hub/configuration/reference-crs/optional/lso/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lso
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: {{ .Values.global.pattern }}
spec:
  project: infra
  source:
    repoURL: {{ .Values.telcoHub.git.repoURL }}
    targetRevision: {{ .Values.telcoHub.git.targetRevision }}
    path: telco-hub/configuration/reference-crs/optional/lso
{{- if .Values.telcoHub.lso.kustomizePatches }}
    kustomize:
      patches:
{{- range .Values.telcoHub.lso.kustomizePatches }}
        - target:
{{- if .target.group }}
            group: {{ .target.group }}
{{- end }}
{{- if .target.version }}
            version: {{ .target.version }}
{{- end }}
            kind: {{ .target.kind }}
{{- if .target.name }}
            name: {{ .target.name }}
{{- end }}
{{- if .target.namespace }}
            namespace: {{ .target.namespace }}
{{- end }}
          patch: |-
{{ .patch | indent 12 }}
{{- end }}
{{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
{{- with .Values.telcoHub.argocd.syncPolicy }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}

{{- if .Values.telcoHub.components.odf.enabled }}
---
# OpenShift Data Foundation - Referenced from existing telco-hub/configuration/reference-crs/optional/odf-internal/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: {{ .Values.global.pattern }}
spec:
  project: infra
  source:
    repoURL: {{ .Values.telcoHub.git.repoURL }}
    targetRevision: {{ .Values.telcoHub.git.targetRevision }}
    path: telco-hub/configuration/reference-crs/optional/odf-internal
{{- if .Values.telcoHub.odf.kustomizePatches }}
    kustomize:
      patches:
{{- range .Values.telcoHub.odf.kustomizePatches }}
        - target:
{{- if .target.group }}
            group: {{ .target.group }}
{{- end }}
{{- if .target.version }}
            version: {{ .target.version }}
{{- end }}
            kind: {{ .target.kind }}
{{- if .target.name }}
            name: {{ .target.name }}
{{- end }}
{{- if .target.namespace }}
            namespace: {{ .target.namespace }}
{{- end }}
          patch: |-
{{ .patch | indent 12 }}
{{- end }}
{{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
{{- with .Values.telcoHub.argocd.syncPolicy }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}


{{- if .Values.telcoHub.components.backupRecovery.enabled }}
---
# Backup and Recovery - Referenced from existing telco-hub/configuration/reference-crs/optional/backup-recovery/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backup-recovery
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: {{ .Values.global.pattern }}
spec:
  project: infra
  source:
    repoURL: {{ .Values.telcoHub.git.repoURL }}
    targetRevision: {{ .Values.telcoHub.git.targetRevision }}
    path: telco-hub/configuration/reference-crs/optional/backup-recovery
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
{{- with .Values.telcoHub.argocd.syncPolicy }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}

{{- if .Values.telcoHub.components.logging.enabled }}
---
# Logging - Referenced from existing telco-hub/configuration/reference-crs/optional/logging/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: {{ .Values.global.pattern }}
spec:
  project: infra
  source:
    repoURL: {{ .Values.telcoHub.git.repoURL }}
    targetRevision: {{ .Values.telcoHub.git.targetRevision }}
    path: telco-hub/configuration/reference-crs/optional/logging
{{- if .Values.telcoHub.logging.kustomizePatches }}
    kustomize:
       patches:
{{- range .Values.telcoHub.logging.kustomizePatches }}
         - target:
{{- if .target.group }}
             group: {{ .target.group }}
{{- end }}
{{- if .target.version }}
             version: {{ .target.version }}
{{- end }}
             kind: {{ .target.kind }}
{{- if .target.name }}
             name: {{ .target.name }}
{{- end }}
{{- if .target.namespace }}
             namespace: {{ .target.namespace }}
{{- end }}
           patch: |-
{{ .patch | indent 12 }}
{{- end }}
{{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
{{- with .Values.telcoHub.argocd.syncPolicy }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
